name: "Build and deploy backend maven fss (prod, q0, q1)"

on:
  workflow_call:
    inputs:
      path:
        required: false
        default: ""
        type: string
      team:
        required: true
        type: string
      nais-template-production:
        required: true
        type: string
      nais-template-q0:
        required: true
        type: string
      nais-template-q1:
        required: true
        type: string

jobs:
  build-backend-and-publish-docker:
    if: github.ref == 'refs/heads/main'
    name: Build backend application
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: cd .${{ inputs.path }} && mvn -B package --file pom.xml

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: pensjon-person
          dockerfile: .${{ inputs.path }}/Dockerfile
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build-backend-and-publish-docker
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-prod-q0-q1.yml@main
    with:
      image: ${{ needs.build-backend-and-publish-docker.outputs.image }}
      nais-template-production: ${{ inputs.nais-template-production }}
      nais-template-q0: ${{ inputs.nais-template-q0 }}
      nais-template-q1: ${{ inputs.nais-template-q1 }}
      team: ${{ inputs.team }}
