name: "Build frontend"

on:
  workflow_call:
    inputs:
      path:
        required: false
        default: ""
        type: string
      node_version:
        required: false
        type: string
        default: "18.18.1"

jobs:
  build-frontend:
    name: Build frontend application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: 'https://npm.pkg.github.com'
          cache: npm
          cache-dependency-path: ${{ inputs.path }}/package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Build application
        run: npm run ${{ inputs.build_script_command }}
