name: "Build and deploy backend maven fss (prod, q0, q1)"

on:
  workflow_call:
    inputs:
      path:
        required: false
        default: ""
        type: string
      team:
        required: true
        type: string
      nais-template-production:
        required: true
        type: string
      nais-template-q0:
        required: true
        type: string
      nais-template-q1:
        required: true
        type: string

jobs:
  build-backend-and-publish-docker:
    name: Build backend application
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/build-backend-and-publish-docker.yml@main
    permissions:
      contents: "read"
      id-token: "write"
    with:
      path: ${{ inputs.path }}
    secrets: inherit

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: pensjon-person
          dockerfile: .${{ inputs.path }}/Dockerfile
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build-backend-and-publish-docker
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-prod-q0-q1.yml@main
    with:
      image: ${{ needs.build-backend-and-publish-docker.outputs.image }}
      nais-template-production: ${{ inputs.nais-template-production }}
      nais-template-q0: ${{ inputs.nais-template-q0 }}
      nais-template-q1: ${{ inputs.nais-template-q1 }}
      team: ${{ inputs.team }}
