name: "Build and deploy backend"

on:
  workflow_call:
    inputs:
      app:
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      path:
        required: false
        default: ""
        type: string
      nais-template:
        required: true
        type: string

jobs:
  build-backend:
    name: Build backend application
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: cd .${{ inputs.path }} && mvn -B package --file pom.xml

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: pensjon-person
          dockerfile: .${{ inputs.path }}/Dockerfile
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  trivy-docker:
    needs: build-backend
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/trivy-docker.yml@main
    with:
      image: ${{ needs.build-backend.outputs.image }}
    secrets: inherit

  deploy:
    needs: build-backend
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy.yml@main
    with:
      image: ${{ needs.build-backend.outputs.image }}
      nais-template: ${{ inputs.nais-template }}
