name: "Build and deploy backend maven fss (prod, q0, q1)"

on:
  workflow_call:
    inputs:
      path:
        required: false
        default: ""
        type: string
      team:
        required: true
        type: string
      nais-template-production:
        required: true
        type: string
      nais-template-q0:
        required: true
        type: string
      nais-template-q1:
        required: true
        type: string
      cluster:
        required: true
        type: string

jobs:
  build-backend-and-publish-docker:
    name: Build backend application
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/build-backend-and-publish-docker.yml@main
    permissions:
      contents: "read"
      id-token: "write"
    with:
      path: ${{ inputs.path }}
    secrets: inherit

  trivy-docker:
    needs: build-backend-and-publish-docker
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/trivy-docker.yml@main
    with:
      image: ${{ needs.build-backend-and-publish-docker.outputs.image }}
    secrets: inherit

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build-backend-and-publish-docker
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-prod-q0-q1.yml@main
    with:
      image: ${{ needs.build-backend-and-publish-docker.outputs.image }}
      nais-template-production: ${{ inputs.nais-template-production }}
      nais-template-q0: ${{ inputs.nais-template-q0 }}
      nais-template-q1: ${{ inputs.nais-template-q1 }}
      team: ${{ inputs.team }}
      cluster: ${{ inputs.cluster }}
