name: Build and deploy backend maven to q2

on:
  workflow_call:
    inputs:
      path:
        required: false
        default: ""
        type: string
      nais-template:
        required: true
        type: string
      team:
        required: true
        type: string
      cluster:
        required: true
        type: string

jobs:
  build-backend-and-publish-docker:
    name: Build backend application
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/build-backend-and-publish-docker.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      path: ${{ inputs.path }}
    secrets: inherit

  trivy-docker:
    needs: build-backend-and-publish-docker
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/trivy-docker.yml@main
    with:
      image: ${{ needs.build-backend-and-publish-docker.outputs.image }}
    secrets: inherit

  deploy:
    needs: build-backend-and-publish-docker
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-q2.yml@attempt-to-pass-cluster-as-environment
    with:
      image: ${{ needs.build-backend-and-publish-docker.outputs.image }}
      nais-template: ${{ inputs.nais-template }}
      team: ${{ inputs.team }}
      cluster: ${{ inputs.cluster }}
