name: "Build and deploy backend"

on:
  workflow_call:
    inputs:
      app:
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      path:
        required: false
        default: ""
        type: string
      nais-template:
        required: true
        type: string

jobs:
  build-backend-and-publish-docker:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/build-java-and-publish-docker.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      path: ${{ inputs.path }}
    secrets: inherit

  trivy-docker:
    needs: build-backend-and-publish-docker
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/trivy-docker.yml@main
    with:
      image: ${{ needs.build-backend-and-publish-docker.outputs.image }}
    secrets: inherit

  deploy:
    needs: build-backend-and-publish-docker
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy.yml@main
    with:
      image: ${{ needs.build-backend-and-publish-docker.outputs.image }}
      nais-template: ${{ inputs.nais-template }}
