name: deploy q2

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      nais-template:
        required: true
        type: string
      team:
        required: true
        type: string
      cluster:
        required: true
        type: string

jobs:
  deploy-to-q2:
    name: Deploy til q2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy q2
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-${{ inputs.cluster }}
          RESOURCE: ${{ inputs.nais-template }}
          IMAGE: ${{ inputs.image }}
          TEAM: ${{ inputs.team }}
