name: Deploy to prod, q0 and q1

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      nais-template-production:
        required: true
        type: string
      nais-template-q0:
        required: true
        type: string
      nais-template-q1:
        required: true
        type: string
      team:
        required: true
        type: string

jobs:
  deployQ:
    name: Deploy to Q environments
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - envclass: q
            environment: q0
            naisyaml: ${{ inputs.nais-template-q0 }}
          - envclass: q
            environment: q1
            naisyaml: ${{ inputs.nais-template-q1 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: ${{ matrix.naisyaml }}
          IMAGE: ${{ inputs.image }}
          TEAM: ${{ inputs.team }}

  deployProd:
    name: Deploy to prod
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Deploy to prod-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: ${{ inputs.nais-template-production }}
          IMAGE: ${{ inputs.image }}
          TEAM: ${{ inputs.team }}
