name: deploy q2

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      nais-template:
        required: true
        type: string
      team:
        required: true
        type: string
      cluster:
        required: false
        default: dev-fss
        type: string

jobs:
  deploy-to-q2:
    name: Deploy til q2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: ${{ inputs.nais-template }}
          IMAGE: ${{ inputs.image }}
          TEAM: ${{ inputs.team }}
